import { Router, type IRouter } from "express";
import healthRouter from "./health";
import dashboardRouter from "./dashboard";
import projectsRouter from "./projects";
import landProspectsRouter from "./land-prospects";
import feasibilityRouter from "./feasibility";
import legalRouter from "./legal";
import leadsRouter from "./leads";
import customersRouter from "./customers";
import unitsRouter from "./units";
import constructionRouter from "./construction";
import qcRouter from "./qc";
import materialsRouter from "./materials";
import handoversRouter from "./handovers";
import aiAnalyzeRouter from "./ai-analyze";
import aiRoadmapRouter from "./ai-roadmap";
import aiLandAssessmentRouter from "./ai-land-assessment";
import aiSlisChatRouter from "./ai-slis-chat";
import aiKabupatenInsightRouter from "./ai-kabupaten-insight";
import planningMarketRouter from "./planning-market";
import planningLandRouter from "./planning-land";
import planningProductRouter from "./planning-product";
import planningFeasibilityRouter from "./planning-feasibility";
import planningMilestonesRouter from "./planning-milestones";
import planningCashflowRouter from "./planning-cashflow";
import planningKppRouter from "./planning-kpp";
import planningSDMRouter from "./planning-sdm";
import planningLandbankRouter from "./planning-landbank";
import aiPlanningInsightRouter from "./ai-planning-insight";
import expansionRouter from "./expansion";
import subkonRouter from "./subkon";
import fasumRouter from "./fasum";
import prodMaterialRouter from "./prod-material";
import unitQcReworkRouter from "./unit-qc-rework";
import prodDashboardRouter from "./prod-dashboard";
import administrasiRouter from "./administrasi";

const router: IRouter = Router();

router.use(healthRouter);
router.use(dashboardRouter);
router.use(projectsRouter);
router.use(landProspectsRouter);
router.use(feasibilityRouter);
router.use(legalRouter);
router.use(leadsRouter);
router.use(customersRouter);
router.use(unitsRouter);
router.use(constructionRouter);
router.use(qcRouter);
router.use(materialsRouter);
router.use(handoversRouter);
router.use(aiAnalyzeRouter);
router.use(aiRoadmapRouter);
router.use(aiLandAssessmentRouter);
router.use(aiSlisChatRouter);
router.use(aiKabupatenInsightRouter);
router.use(planningMarketRouter);
router.use(planningLandRouter);
router.use(planningProductRouter);
router.use(planningFeasibilityRouter);
router.use(planningMilestonesRouter);
router.use(planningCashflowRouter);
router.use(planningKppRouter);
router.use(planningSDMRouter);
router.use(planningLandbankRouter);
router.use(aiPlanningInsightRouter);
router.use(expansionRouter);
router.use(subkonRouter);
router.use(fasumRouter);
router.use(prodMaterialRouter);
router.use(unitQcReworkRouter);
router.use(prodDashboardRouter);
router.use(administrasiRouter);

export default router;
